In [1]:
import tensorflow as tf
from tensorflow.python.keras import regularizers
import pandas as pd
from tensorflow.python.ops import nn
import numpy as np
from models import MyModel,MyDenseLayer, cal_acc
if tf.__version__ != "2.0.0":
    tf.enable_eager_execution()
def my_loss(y_pred,y_true):
    y_true = tf.one_hot(y_true, n_outputs, dtype=tf.float32)
    return  tf.reduce_mean(tf.keras.losses.categorical_crossentropy(y_true,y_pred))
"""
    Hyper-parameters
"""
n_inputs = 28*28
n_outputs = 10
n_hiddens = 200
n_epochs = 5
n_batches = 1000
epoch = 0
target_loss = 1e-5
thresh_hold = 1e-4
"""
    Load data
"""
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train = x_train.reshape((len(x_train),28*28))
x_test = x_test.reshape((len(x_test),28*28))
train_dataset = tf.data.Dataset.from_tensor_slices((x_train,y_train)).shuffle(len(x_train)).batch(n_batches)
"""
    Train data
"""
m_model = MyModel()
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
epoch = 0
while (epoch < n_epochs) or (epoch_loss_avg.result() < target_loss):
    epoch += 1
    epoch_loss_avg = tf.keras.metrics.Mean()
    accuracy = 0
    for x, y in train_dataset:
        with tf.GradientTape() as tape:
            out_sm = m_model(x)
            batch_loss = my_loss(out_sm, y)
            variables = m_model.trainable_variables
            grads = tape.gradient(batch_loss, variables)
            optimizer.apply_gradients(zip(grads, variables))
        epoch_loss_avg(batch_loss)
    if epoch%1 == 0:
        print(m_model.summary())
    test_out = m_model(x_test)
    accuracy = cal_acc(test_out, y_test)
    m_model.sparsify_weights()
    m_model.add_layer()
    print('Epoch : {} ----- Loss : {} ----- Acc : {}'.format(epoch, epoch_loss_avg.result(), accuracy))


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Model: "my_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input (MyDenseLayer)         multiple                  157000    
_________________________________________________________________
output (MyDenseLayer)        multiple                  2010      
Total params: 159,010
Trainable params: 159,010
Non-trainable params: 0
_________________________________________________________________
None
Epoch : 1 ----- L

In [4]:
m_model = MyModel()

<tf.Tensor: id=8284, shape=(10,), dtype=float32, numpy=
array([0.10048118, 0.10995017, 0.09862196, 0.10275455, 0.09594902,
       0.08713035, 0.09923879, 0.10736267, 0.09792877, 0.10058253],
      dtype=float32)>

In [5]:
out_sm = m_model(x)
batch_loss = my_loss(out_sm, y)

In [6]:
batch_loss

<tf.Tensor: id=8320, shape=(), dtype=float32, numpy=2.300185>

In [7]:
variables = m_model.trainable_variables

In [2]:
m_model.variables

[<tf.Variable 'my_model/input/kernel_input:0' shape=(784, 200) dtype=float32, numpy=
 array([[ 0.0752743 , -0.        , -0.        , ..., -0.        ,
          0.03316337,  0.04304739],
        [-0.        ,  0.03099629, -0.        , ...,  0.07792288,
          0.04022366, -0.        ],
        [-0.        , -0.        , -0.        , ...,  0.0294874 ,
         -0.        ,  0.02643408],
        ...,
        [ 0.06801196, -0.        ,  0.07044581, ...,  0.02388632,
         -0.        , -0.        ],
        [-0.        , -0.        ,  0.06191622, ..., -0.        ,
          0.04253362,  0.08460927],
        [ 0.00329512, -0.        ,  0.01748352, ...,  0.07263636,
         -0.        , -0.        ]], dtype=float32)>,
 <tf.Variable 'my_model/input/bias_input:0' shape=(200,) dtype=float32, numpy=
 array([ 0.07353179,  0.04345268, -0.        ,  0.01840195,  0.11543401,
         0.06522939,  0.0953796 ,  0.00277599, -0.        , -0.        ,
         0.06876204, -0.        , -0.        , 

In [8]:
for x, y in train_dataset:
    with tf.GradientTape() as tape:
        out_sm = m_model(x)
        batch_loss = my_loss(out_sm, y)
        variables = m_model.trainable_variables
        grads = tape.gradient(batch_loss, variables)
        optimizer.apply_gradients(zip(grads, variables))

[<tf.Tensor: id=34126, shape=(784, 200), dtype=float32, numpy=
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: id=34125, shape=(200,), dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
     